routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});


Auth::routes();
/*Route::group(['prefix' => 'ringless'], function () {


    Auth::routes();


});*/
Route::get('/home', 'HomeController@index')->name('home');
/*
Route::get('/test', function () {
        return view('test');
    });
*/
Route::get('/test', 'TestController@index')->name('test');

Route::post('/call','TestController@call');

Route::get('/status', 'TestController@status')->name('status');

Route::get('/execute-status', 'TestCallerController@execute_status');


Route::get('/testcaller', 'TestCallerController@index')->name('test.caller');

Route::post('/calling','TestCallerController@call')->name('testcall');


Route::resource('trunk', 'TrunkController');

Route::resource('country', 'CountryController');

Route::resource('campaign', 'CampaignController');

Route::resource('numbers', 'NumbersController');

Route::resource('run', 'RunController');

Route::post('/run/{run}', ['as' => 'run.update', 'uses' => 'RunController@update']);

Route::get('run-pause/{run}', 'RunController@pause')->name('run.pause');

Route::get('run-start/{run}', 'RunController@start')->name('run.start');

Route::get('ami-channels', 'RunController@ami')->name('run.ami');

#route to download file
Route::get('get-file/{filename}', ['as' => 'numbers.download', 'uses' => 'NumbersController@get_file']);

Route::get('delete-file/{filename}', ['as' => 'numbers.del', 'uses' => 'NumbersController@delete_file']);

Route::get('/changePassword','HomeController@showChangePasswordForm');

Route::post('/changePassword','HomeController@changePassword')->name('changePassword');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('audio-upload', 'AudioUploadController@audioUpload')->name('audio.upload');

//Route::get('audio-list', 'AudioController@index')->name('audio.list');

//Route::get('audio-play/{filename}', 'AudioController@play_audio')->name('audio.play');

//Route::get('audio-delete/{filename}', 'AudioController@delete_file')->name('audio.del');

//Route::post('audio-upload', 'AudioUploadController@audioUploadPost')->name('audio.upload.post');

app/Campaign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    //
    protected $table = 'campaign';
    protected $fillable = [ 'name', 'description'];

    /**
     * Get the number for the Campaign.
     */
    public function numbers()
    {
        return $this->hasMany('App\Numbers', 'campaignid', 'id');
    }

    /**
     * Get the Run for the Campaign.
     */
    public function run()
    {
        return $this->hasOne('App\Run', 'campaignid', 'id');
    }

}

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Campaign;


class CampaignController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $campaigns = Campaign::all();
        return view('campaign.index', compact('campaigns'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('campaign.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         //
        $request->validate([
            'campaign_name' => 'required|unique:campaign,name'
        ]);
        $campaign = new Campaign([ 
            'name' => $request->get('campaign_name'),
            'description' => $request->get('campaign_description')
        ]);
        $campaign->save();
        return redirect('/campaign')->with('success', 'Campaign has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $campaign = Campaign::find($id);
        return view('campaign.edit', compact('campaign'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        /*$request->validate([
            'campaign_name' => 'required|unique:campaign,name'
        ]);*/

        $campaign = Campaign::find($id);
        $campaign->name = $request->get('campaign_name');
        $campaign->description = $request->get('campaign_description');
        $campaign->save();
        return redirect('/campaign')->with('success', 'Campaign has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $campaign = Campaign::find($id);
        $campaign->delete();
        return redirect('/campaign')->with('Success', 'campaign has been Deleted Successfully');
    }
}

resources/views/campaign/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Campaign')

@section('content_header')
    <h1>Create Campaign</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Campaign
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('campaign.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Campaign Name:</label>
              <input type="text" class="form-control" name="campaign_name"/>
          </div>
          <div class="form-group">
              <label for="ip">Campaign Description :</label>
              <input type="text" class="form-control" name="campaign_description"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@stop

@section('css')
    
@stop

@section('js')
  
@stop

resources/views/campaign/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Campaign')

@section('content_header')
    <h1>Update Campaign</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Trunk
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('campaign.update', $campaign->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">Campaign Name:</label>
          <input type="text" class="form-control" name="campaign_name" value={{ $campaign->name }} />
        </div>
        <div class="form-group">
          <label for="trunk_ip">Campaign Description :</label>
          <input type="text" class="form-control" name="campaign_description" value={{ $campaign->description }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@stop

@section('css')
    
@stop

@section('js')
    
@stop

resources/views/campaign/index.blade.php
@extends('adminlte::page')

@section('title', 'List Campaigns')

@section('content_header')
    <h1>Campaigns </h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Campaing Name</td>
          <td>Campaign Description</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($campaigns as $campaign)
        <tr>
            <td>{{$campaign->id}}</td>
            <td>{{$campaign->name}}</td>
            <td>{{$campaign->description}}</td>
            <td><a href="{{ route('campaign.edit',$campaign->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('campaign.destroy', $campaign->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@stop