routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});


Auth::routes();
/*Route::group(['prefix' => 'ringless'], function () {


    Auth::routes();


});*/
Route::get('/home', 'HomeController@index')->name('home');
/*
Route::get('/test', function () {
        return view('test');
    });
*/
Route::get('/test', 'TestController@index')->name('test');

Route::post('/call','TestController@call');

Route::get('/status', 'TestController@status')->name('status');

Route::get('/execute-status', 'TestCallerController@execute_status');


Route::get('/testcaller', 'TestCallerController@index')->name('test.caller');

Route::post('/calling','TestCallerController@call')->name('testcall');


Route::resource('trunk', 'TrunkController');

Route::resource('country', 'CountryController');

Route::resource('campaign', 'CampaignController');

Route::resource('numbers', 'NumbersController');

Route::resource('run', 'RunController');

Route::post('/run/{run}', ['as' => 'run.update', 'uses' => 'RunController@update']);

Route::get('run-pause/{run}', 'RunController@pause')->name('run.pause');

Route::get('run-start/{run}', 'RunController@start')->name('run.start');

Route::get('ami-channels', 'RunController@ami')->name('run.ami');

#route to download file
Route::get('get-file/{filename}', ['as' => 'numbers.download', 'uses' => 'NumbersController@get_file']);

Route::get('delete-file/{filename}', ['as' => 'numbers.del', 'uses' => 'NumbersController@delete_file']);

Route::get('/changePassword','HomeController@showChangePasswordForm');

Route::post('/changePassword','HomeController@changePassword')->name('changePassword');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('audio-upload', 'AudioUploadController@audioUpload')->name('audio.upload');

//Route::get('audio-list', 'AudioController@index')->name('audio.list');

//Route::get('audio-play/{filename}', 'AudioController@play_audio')->name('audio.play');

//Route::get('audio-delete/{filename}', 'AudioController@delete_file')->name('audio.del');

//Route::post('audio-upload', 'AudioUploadController@audioUploadPost')->name('audio.upload.post');

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    //
    protected $primaryKey = 'country_code';
    public $incrementing = false;
    protected $table = 'country';
    protected $fillable = ['country_code', 'name'];

    /**
     * Get the Numbers for the Country.
     */
    public function run()
    {
        return $this->hasMany('App\Run', 'country_code', 'country_code');
    }
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Country;

class CountryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $countries = Country::all();
        return view('country.index', compact('countries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('country.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'country_code' => 'required|unique:country,country_code',
            'country_name' => 'required|unique:country,name'
        ]);
        $country = new Country([ 
            'country_code' => $request->get('country_code'),
            'name' => $request->get('country_name')
        ]);
        $country->save();
        return redirect('/country')->with('success', 'Country has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $country = country::find($id);
        return view('country.edit', compact('country'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'country_name' => 'required|unique:country,name'
        ]);

        $country = Country::find($id);
        $country->name = $request->get('country_name');

        $country->save();
        return redirect('/country')->with('success', 'Country has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $country = Country::find($id);
        $country->delete();
        return redirect('/country')->with('Success', 'country has been Deleted Successfully');
    }
}

resources/views/country/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Country')

@section('content_header')
    <h1>Create Country</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Country
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('country.store') }}">
          <div class="form-group">
              @csrf
              <label for="country_code">Country code:</label>
              <input type="text" class="form-control" name="country_code"/>
          </div>
          <div class="form-group">
              <label for="country_name">Country Name :</label>
              <input type="text" class="form-control" name="country_name"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@stop

@section('css')
    
@stop

@section('js')
    
@stop

resources/views/country/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Country')

@section('content_header')
    <h1>Update Country</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Country
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('country.update', $country->country_code) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="country_name">Country Name :</label>
          <input type="text" class="form-control" name="country_name" value={{ $country->name }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/country/index.blade.php
@extends('adminlte::page')

@section('title', 'List Countries')

@section('content_header')
    <h1>Countries </h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Code Country</td>
          <td>Country Name</td>
          
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($countries as $country)
        <tr>
            <td>{{$country->country_code}}</td>
            <td>{{$country->name}}</td>
            <td><a href="{{ route('country.edit', $country->country_code )}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('country.destroy', $country->country_code)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@stop