routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});


Auth::routes();
/*Route::group(['prefix' => 'ringless'], function () {


    Auth::routes();


});*/
Route::get('/home', 'HomeController@index')->name('home');
/*
Route::get('/test', function () {
        return view('test');
    });
*/
Route::get('/test', 'TestController@index')->name('test');

Route::post('/call','TestController@call');

Route::get('/status', 'TestController@status')->name('status');

Route::get('/execute-status', 'TestCallerController@execute_status');


Route::get('/testcaller', 'TestCallerController@index')->name('test.caller');

Route::post('/calling','TestCallerController@call')->name('testcall');


Route::resource('trunk', 'TrunkController');

Route::resource('country', 'CountryController');

Route::resource('campaign', 'CampaignController');

Route::resource('numbers', 'NumbersController');

Route::resource('run', 'RunController');

Route::post('/run/{run}', ['as' => 'run.update', 'uses' => 'RunController@update']);

Route::get('run-pause/{run}', 'RunController@pause')->name('run.pause');

Route::get('run-start/{run}', 'RunController@start')->name('run.start');

Route::get('ami-channels', 'RunController@ami')->name('run.ami');

#route to download file
Route::get('get-file/{filename}', ['as' => 'numbers.download', 'uses' => 'NumbersController@get_file']);

Route::get('delete-file/{filename}', ['as' => 'numbers.del', 'uses' => 'NumbersController@delete_file']);

Route::get('/changePassword','HomeController@showChangePasswordForm');

Route::post('/changePassword','HomeController@changePassword')->name('changePassword');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('audio-upload', 'AudioUploadController@audioUpload')->name('audio.upload');

//Route::get('audio-list', 'AudioController@index')->name('audio.list');

//Route::get('audio-play/{filename}', 'AudioController@play_audio')->name('audio.play');

//Route::get('audio-delete/{filename}', 'AudioController@delete_file')->name('audio.del');

//Route::post('audio-upload', 'AudioUploadController@audioUploadPost')->name('audio.upload.post');

app/Trunk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trunk extends Model
{
    //
    protected $table = 'trunk';
    protected $fillable = [
    	'id',
    	'name',
    	'ip_address',
    	'connection_string'
    ];
}

app/Http/Controllers/TrunkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Trunk;

class TrunkController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $trunks = Trunk::orderBy('name')->get();
        return view('trunk.index', compact('trunks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('trunk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'trunk_name' => 'required|unique:trunk,name',
            'trunk_ip' => 'required|unique:trunk,ip_address',
            'trunk_connection' => 'required|unique:trunk,connection_string'
        ]);
        $trunk = new Trunk([ 
            'name' => $request->get('trunk_name'),
            'ip_address' => $request->get('trunk_ip'),
            'connection_string' => $request->get('trunk_connection')
        ]);
        $trunk->save();
        return redirect('/trunk')->with('success', 'Trunk has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $trunk = Trunk::find($id);
        return view('trunk.edit', compact('trunk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
       /* $request->validate([
            'trunk_name' => 'required|unique:trunk,name',
            'trunk_ip' => 'required|unique:trunk,ip_address',
            'trunk_connection' => 'required|unique:trunk,connection_string'
        ]);*/

        $trunk = Trunk::find($id);
        $trunk->name = $request->get('trunk_name');
        $trunk->ip_address = $request->get('trunk_ip');
        $trunk->connection_string = $request->get('trunk_connection');

        $trunk->save();
        return redirect('/trunk')->with('success', 'Trunk has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $trunk = Trunk::find($id);
        $trunk->delete();
        return redirect('/trunk')->with('Success', 'Trunk has been Deleted Successfully');
    }
}

resources/views/trunk/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Trunk')

@section('content_header')
    <h1>Create Trunk</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Trunk
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('trunk.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Trunk Name:</label>
              <input type="text" class="form-control" name="trunk_name"/>
          </div>
          <div class="form-group">
              <label for="ip">Trunk IP Address :</label>
              <input type="text" class="form-control" name="trunk_ip"/>
          </div>
          <div class="form-group">
              <label for="connection">Trunk Connection String :</label>
              <input type="text" class="form-control" name="trunk_connection"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/trunk/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Trunk')

@section('content_header')
    <h1>Update Trunk</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Trunk
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('trunk.update', $trunk->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">Trunk Name:</label>
          <input type="text" class="form-control" name="trunk_name" value={{ $trunk->name }} />
        </div>
        <div class="form-group">
          <label for="trunk_ip">Trunk IP Address :</label>
          <input type="text" class="form-control" name="trunk_ip" value={{ $trunk->ip_address }} />
        </div>
        <div class="form-group">
          <label for="connection_string">Trunk Connection String:</label>
          <input type="text" class="form-control" name="trunk_connection" value={{ $trunk->connection_string }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/trunk/index.blade.php
@extends('adminlte::page')

@section('title', 'List Trunks')

@section('content_header')
    <h1>Trunks </h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Trunk Name</td>
          <td>Trunk IP Address</td>
          <td>Trunk Connection String</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($trunks as $trunk)
        <tr>
            <td>{{$trunk->id}}</td>
            <td>{{$trunk->name}}</td>
            <td>{{$trunk->ip_address}}</td>
            <td>{{$trunk->connection_string}}</td>
            <td><a href="{{ route('trunk.edit',$trunk->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('trunk.destroy', $trunk->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@stop