routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
//    return view('welcome');
    return view('auth.login');
});


Auth::routes();
/*Route::group(['prefix' => 'ringless'], function () {


    Auth::routes();


});*/
Route::get('/home', 'HomeController@index')->name('home');
/*
Route::get('/test', function () {
        return view('test');
    });
*/
Route::get('/test', 'TestController@index')->name('test');

Route::post('/call','TestController@call');

Route::get('/status', 'TestController@status')->name('status');

Route::get('/execute-status', 'TestCallerController@execute_status');


Route::get('/testcaller', 'TestCallerController@index')->name('test.caller');

Route::post('/calling','TestCallerController@call')->name('testcall');


Route::resource('trunk', 'TrunkController');

Route::resource('country', 'CountryController');

Route::resource('campaign', 'CampaignController');

Route::resource('numbers', 'NumbersController');

Route::resource('run', 'RunController');

Route::post('/run/{run}', ['as' => 'run.update', 'uses' => 'RunController@update']);

Route::get('run-pause/{run}', 'RunController@pause')->name('run.pause');

Route::get('run-start/{run}', 'RunController@start')->name('run.start');

Route::get('ami-channels', 'RunController@ami')->name('run.ami');

#route to download file
Route::get('get-file/{filename}', ['as' => 'numbers.download', 'uses' => 'NumbersController@get_file']);

Route::get('delete-file/{filename}', ['as' => 'numbers.del', 'uses' => 'NumbersController@delete_file']);

Route::get('/changePassword','HomeController@showChangePasswordForm');

Route::post('/changePassword','HomeController@changePassword')->name('changePassword');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('audio-upload', 'AudioUploadController@audioUpload')->name('audio.upload');

//Route::get('audio-list', 'AudioController@index')->name('audio.list');

//Route::get('audio-play/{filename}', 'AudioController@play_audio')->name('audio.play');

//Route::get('audio-delete/{filename}', 'AudioController@delete_file')->name('audio.del');

//Route::post('audio-upload', 'AudioUploadController@audioUploadPost')->name('audio.upload.post');

app/Numbers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Numbers extends Model
{
    protected $table        = 'numbers';

    protected $primaryKey   = 'phonenumber';
    
    protected $fillable     = ['phonenumber', 'status', 'campaignid', 'country_code', 'amd_status'];

    /**
     * Get the country for the Number.
     */
    public function country()
    {
        return $this->belongsTo('App\Country', 'country_code');
    }

    /**
     * Get the campaign for the Number.
     */
    public function campaign()
    {
        return $this->belongsTo('App\Campaign', 'campaignid');
    }

}

app/Http/Controllers/NumbersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Country;

use App\Campaign;

use File;

use Illuminate\Support\Facades\Storage;

use Excel;

use App\Numbers;

use DB;

use Carbon\Carbon;

use Response;

class NumbersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //$numbers = Numbers::all();
        $directorio = "/var/www/html/validate/storage/app/reports";
        $filesFolder = \File::files($directorio);
        foreach($filesFolder as $path) { 
          $files[] = pathinfo($path);
        }
        return view('numbers.index', compact('files'));
    }


        /**
        * Download file
        **/
    public function get_file($filename)
    {
        $file_path = storage_path('app/reports') . "/" . $filename;
        return Response::download($file_path);
    }

        /**
        * Delete file
        **/
    public function delete_file($filename)
    {
        $file_path = storage_path('app/reports') . "/" . $filename;
        \File::Delete($file_path);
        return redirect('/numbers')->with('success', 'The file has been deleted');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $countries = Country::all();
        $campaigns = Campaign::all();
        return view('numbers.create', compact('countries','campaigns'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //Get field from form
        $file = $request->file('numbers_phonenumbers');

        //Get name file
        $name = $file->getClientOriginalName();

        $filename = pathinfo($name, PATHINFO_FILENAME);

        $campaign = (int) $request->get('numbers_campaignid');

        $c_code = $request->get('numbers_country_code');

        //dd($campaign);
        //Store de new file in local disk
        Storage::disk('local')->put($name, File::get($file));
        $path_1 = 'app/numbers/'.$name;
        $path = 'app/numbers/'.$filename.'.csv';

        //Storage::move(Storage::get(storage_path($path_1)), Storage::get(storage_path($path)));

        $filename = str_replace("\\", "/", storage_path($path_1));

        $query = "LOAD DATA LOCAL INFILE '".$filename."' IGNORE INTO TABLE numbers (phonenumber);";

        DB::unprepared($query);

        $date = Carbon::now();

        DB::update('update ignore numbers set status = "new", campaignid = ?, country_code = ?, created_at = ?, updated_at = ? where campaignid is NULL and country_code is NULL', [$campaign,$c_code,$date,$date]);

        $amount = DB::table('numbers')
                     ->select(DB::raw('count(*) as cnt'))
                     ->where('created_at', $date)
                     ->first();

       (array)$success = 'has been added to Campaign';

       $camp = Campaign::find($campaign);

        DB::delete('delete from numbers where campaignid is NULL and country_code is NULL and status is NULL');

       $c = json_decode($camp);

       $directorio = "/var/www/html/validate/storage/app/reports";
        $filesFolder = \File::files($directorio);
        foreach($filesFolder as $path) { 
          $files[] = pathinfo($path);
        }

       return view('numbers.index',compact('amount','success','c','files'));
            
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/numbers/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Numbers')

@section('content_header')
    <h1>Add Numbers</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Numbers
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('numbers.store') }}" enctype="multipart/form-data">
          <div class="form-group">
              @csrf
              <label for="numbers_country_code">Country :</label>
              <select name="numbers_country_code">
                @foreach ($countries as $country)
                  <option value="{{ $country->country_code }} "> {{$country->name}}</option>
                @endforeach 
              </select>
          </div>

          <div class="form-group">
              <label for="numbers_campaign">Campaign :</label>
              <select name="numbers_campaignid">
                @foreach ($campaigns as $campaign)
                  <option value="{{ $campaign->id }} "> {{$campaign->name}}</option>
                @endforeach 
              </select>
          </div>

          <div class="form-group">
              <label for="numbers_phonenumbers">Phonenumbers File :</label>
              <input type="file" name="numbers_phonenumbers"  class="form-control">
          </div>
              
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@stop

@section('css')
    
@stop

@section('js')
    
@stop

resources/views/numbers/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Country')

@section('content_header')
    <h1>Update Country</h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Country
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('country.update', $country->country_code) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="country_name">Country Name :</label>
          <input type="text" class="form-control" name="country_name" value={{ $country->name }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/numbers/index.blade.php
@extends('adminlte::page')

@section('title', 'List Numbers')

@section('content_header')
    <h1>Generated Reports of Numbers with answer MACHINE </h1>
@stop

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}  
    </div><br />
  @endif
  @isset($amount)
  <div class="alert alert-success">
      @foreach ($amount as $cnt)
        <strong> {{ $cnt }} Numbers </strong>
      @endforeach
  @endisset
  @isset($success)
        {{$success}}
  @endisset
  @isset($c)
        <strong>{{ $c->name }}</strong>
    </div>
  @endisset
        
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Filename</td>
          <td colspan="3">Actions</td>
        </tr>
    </thead>
    <tbody>
      @isset($files)
        @foreach($files as $file)
        <tr>
            <td>{{$file['basename']}}</td>
            <td><a href="{{ route('numbers.download',$file['basename'])}}" class="btn btn-primary">Download</a></td>
            <td><a href="{{ route('numbers.del',$file['basename'])}}" class="btn btn-danger">Delete</a></td>
        </tr>
        @endforeach
      @endisset
    </tbody>
  </table>
   
  </table>
<div>
@stop